Add support for prefill parameter salesforce_uuid
tcampb/react-calendly pull request #128
Opened 2022-08-18 17:13 UTC by ramzimaalej

# Summary
This PR adds support to pass `salesfoce_uuid` as defined here under the invitee section:  https://developer.calendly.com/api-docs/decca36cf717f-invitee 

cc @tcampb

2022-08-19 01:23 UTC, tcampb commented on package-lock.json
> +  "version": "4.0.2",
Can you remove this change? I can update the version when I publish the changes to npm.

2022-08-19 01:24 UTC, tcampb requested changes
Thanks for creating this PR, the changes look good! If you can just remove the package-lock file changes I can then merge this PR.

2022-08-26 16:29 UTC, ramzimaalej commented
@tcampb It's done. Thank you for the review!

2022-09-02 20:04 UTC, tcampb approved these changes

2022-09-02 20:04 UTC, merged